debug: true
log:
  dir: "/data/log/"
sqlMap:
  gold:
    dsn: "abc"
    maxIdle: 50
    maxConn: 100
    maxLifeTime: "10m"
redis:
  network: "tcp"
  addr: "172.171.122.10:6379"
  password: "thisispasswd"
  db: 1
  dialTimeout: "200ms"
  readTimeout: "5s"
  writeTimeout: "5s"
  #poolsize is the redis client pool
  poolsize: 100
  #minIdleConns means the minimum of client connections in idle status
  minIdleConns: 50
  idleTimeout: "120s"
rpcServer:
  network: "tcp"
  addr: ":8080"
  timeout: "1s"
  idleTimeout: "60s"
  maxLifeTime: "60s"
  ForceCloseWait: "60s"
  KeepAliveInterval: "60s"
  KeepAliveTimeout: "60s"
  #address for distributed tracing system - jaeger
  jaegerAddr: "172.127.23.175:16831"