debug: true
log:
  dir: "/data/log/config-admin/"
mysql:
  gold:
    #database: stt_choutqin
    #table: member_money_balance, user's gold;
    #table: member_money_balance_new, user's gold from other financing channel;
    #table: member_score, anchor's gain sharing
    #table: chouqin_transaction_journal_new, transaction record
    #table: chouqin_recharge_log, user's recharge log
    #table: chouqin_exchange_journal, anchor's gold change log
    dsn: "web_user:$1$docker$2J0E1LRyED3Af.Mt/ua0O0@tcp(172.17.1.130:3304)/stt_chouqin?charset=utf8&parseTime=True&loc=Local"
    max_idle_connection: 50
    max_connection: 100
    max_life_time: "10m"
redis:
  #key: gold:all:$uid, user's gold number, include all channels
  #key	gold:anchor:$anchorID, anchor's gain sharing
  network: "tcp"
  addr: "172.17.1.130:6379"
  password: "qietvredis"
  db: 1
  dialTimeout: "200ms"
  readTimeout: "5s"
  writeTimeout: "5s"
  #poolsize is the redis client pool
  poolsize: 100
  #minIdleConns means the minimum of client connections in idle status
  minIdleConns: 50
  idleTimeout: "120s"
rpcServer:
  network: "tcp"
  addr: ":8808"
  timeout: "1s"
  idleTimeout: "60s"
  maxLifeTime: "60s"
  ForceCloseWait: "60s"
  KeepAliveInterval: "60s"
  KeepAliveTimeout: "60s"
  #address for distributed tracing system - jaeger
  jaegerAddr: "172.17.3.75:6831"